# after exec 'docker-compose up -d' run this: =>
# => docker-compose exec database mongo --eval "rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'localhost:27017'}]});"

version: '3.1'

services:
  database:
    image: mongo:5
    container_name: mongodb
    restart: always
    command: --replSet rs0
    ports:
      - 27017:27017
    volumes:
      - ~/data/mongo:/data/db
